apiVersion: batch/v1
kind: Job
metadata:
  name: ses-sample
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: ses-sample
        image: ntsutake/ses-sample:latest
